### ISSUE TITLE
Error Initializing Modem and Provision Failure

### ISSUE THREAD

**Issue by troykrahn** [hharte/mm_manager#1] opened 2020-01-23 02:39 UTC
After doing some initial testing, I've noticed a couple issues. 

It seems that after killing the mm_manager process, restarting it often results in "Error Initializing Modem". If I run the command in quick succession it usually works. I'm using a MultiTech MultiModem2 MT5600, which seems to be a Conexant based modem. 

The second issue I'm facing is that the provisioning seems to fail at the exact same spot each time. It appears that table 151 is sent to the phone, then the phone just disconnects. There is an error "ERROR: Got NULL packet without ACK flag set!". I am using VoIP with a Linksys PAP2T ATA, I've tried different jitter settings, as well as using the modem passthrough mode and there's no difference. 

I've attached a screenshot at the point it seems to fail. 

![Screenshot_20200122_160451](https://user-images.githubusercontent.com/32440755/72952216-8fb2b180-3d67-11ea-9a6c-29460f40d0d2.png)

**Comment by hharte** [comment] 2020-01-23 06:30
Hello Troy,

What OS are you using, and what version of firmware is in your phone?  The firmware version info can be displayed through the maintenance menu.  

One thing to try is to just take table 0x97 out of the list of tables in mm_manager.c and see if the phone can download the other tables.

You can also use the -l <file name> and send me the bytestream for analysis.

Thanks for the report,
Howard

**Comment by troykrahn** [comment] 2020-01-23 09:58
Hi Howard,

I'm using Linux, the version of the firmware is as follows (according to what mm_manager sees)

```
Terminal serial number 1234567890, Terminal Status Word: 0x0001000080
Terminal Status: Reserved TELEPHONY_STATUS_BIT_7
Terminal Status: Station Access Cover Opened
                             Terminal Type: 02 (0x02)
                       Control ROM Edition: 12AAV08
                           Control Version: V1.0
                     Telephony ROM Edition: QQ1RWU 
                         Telephony Version: V2.2
                Validator Hardware Version: 60
                Validator Software Version: 12
```
I've tried removing the table to no avail, the next one just fails to send (150).

I've attached the install log so you can have a look.
[install.txt](https://github.com/hharte/mm_manager/files/4102387/install.txt)

**Comment by hharte** [comment] 2020-01-24 04:22
Hello Troy,

Now that you were able to successfully install your phone using NPA1S01 firmware, do you mind if I close this issue?

Please file another one for the "Error Initializing Modem" issue, and add more detail about your setup.  I have not seen this behavior before.

Thanks,
Howard

**Comment by troykrahn** [comment] 2020-01-24 04:46
Howard,

No worries, you may close the issue.

I'll create a new issue for the modem problem.

Troy

**Comment by hharte** [comment] 2020-01-24 04:47
Thanks Troy.

**Closed by hharte** 2020-01-24 04:47 UTC

**Comment by Ritchie828** [comment] 2020-07-27 18:43
This seems to be a common failure point in provisioning. (I currently know of three others with this issue.) I am receiving modem disconnects at the same point as Troy. 
![modem discon](https://user-images.githubusercontent.com/68869656/88577566-d7fba680-d00c-11ea-8f4b-5d547c344bb2.png)
I have confirmed there is communication between the phone and mm_manger as time and date are successfully set and am also receiving some basic info from the phone.
![mill info](https://user-images.githubusercontent.com/68869656/88577898-53f5ee80-d00d-11ea-8fad-427e4ba792b3.png)
You refer to firmware in Troy's issue. Is this something we need to source and change?
